export let ImagesArr=[{
    url:"https://images.hdqwalls.com/wallpapers/tony-stark-the-man-behind-iron-man-xy.jpg",
    id:1,
},{
    url:"https://images.hdqwalls.com/wallpapers/captain-america-protector-of-the-city-jr.jpg",
    id:2
},{
    url:"https://images.hdqwalls.com/wallpapers/spideman-timeless-y3.jpg",
    id:3
},{
    url:"https://images.hdqwalls.com/wallpapers/the-incredible-hulk-mighty-power-4n.jpg",
    id:4
},{
    url:"https://images.hdqwalls.com/wallpapers/hawkeye-arrow-4k-wq.jpg",
    id:5
},{
    url:"https://images.hdqwalls.com/wallpapers/black-widow-girl-cosplay-4k-2z.jpg",
    id:6
}]